# Generated by Django 5.2.1 on 2025-06-05 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código ISO3')),
                ('iso2_code', models.CharField(max_length=2, unique=True, verbose_name='Código ISO2')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('official_name', models.CharField(max_length=150, verbose_name='Nombre oficial')),
                ('phone_code', models.CharField(blank=True, max_length=5, verbose_name='Código telefónico')),
                ('currency_code', models.CharField(blank=True, max_length=3, verbose_name='Código de moneda')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Zona horaria principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DescriptorFamily',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ownership_type', models.CharField(choices=[('PVT', 'Privada'), ('PUB', 'Pública'), ('MIX', 'Mixta'), ('NGO', 'ONG/Sin fines de lucro')], default='PVT', max_length=3, verbose_name='Tipo de propiedad')),
                ('typical_size', models.CharField(blank=True, choices=[('MI', 'Microempresa'), ('SM', 'Pequeña'), ('ME', 'Mediana'), ('LA', 'Grande'), ('EN', 'Corporación')], max_length=2, verbose_name='Tamaño típico')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Organización',
                'verbose_name_plural': 'Tipos de Organización',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(default='--', max_length=2, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('skill_type', models.CharField(choices=[('TE', 'Técnica'), ('SO', 'Blanda'), ('LE', 'Liderazgo'), ('AN', 'Analítica'), ('CR', 'Creativa')], default='TE', max_length=2, verbose_name='Tipo de habilidad')),
                ('typical_level_required', models.CharField(choices=[('BA', 'Básico'), ('IN', 'Intermedio'), ('AD', 'Avanzado'), ('EX', 'Experto')], default='IN', max_length=2, verbose_name='Nivel típico requerido')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['skill_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionOrResponsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('typical_level', models.CharField(blank=True, choices=[('OP', 'Operativo'), ('TA', 'Táctico'), ('ST', 'Estratégico'), ('EX', 'Ejecutivo')], max_length=2, verbose_name='Nivel típico')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_functions', to='world.functionorresponsibility', verbose_name='Función padre')),
            ],
            options={
                'verbose_name': 'Función o Responsabilidad',
                'verbose_name_plural': 'Funciones o Responsabilidades',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ciiu_code', models.CharField(blank=True, max_length=10, verbose_name='Código CIIU')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='world.industry', verbose_name='Industria padre')),
            ],
            options={
                'verbose_name': 'Industria',
                'verbose_name_plural': 'Industrias',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorldDescriptor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='world.descriptorfamily')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='world.worlddescriptor')),
            ],
            options={
                'ordering': ['family__name', 'name'],
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('segment_type', models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Consumer'), ('B2G', 'Business to Government')], default='B2B', max_length=3, verbose_name='Tipo de segmento')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility', verbose_name='Funciones típicas')),
                ('industries', models.ManyToManyField(blank=True, to='world.industry', verbose_name='Industrias relacionadas')),
                ('skills', models.ManyToManyField(blank=True, to='world.skill', verbose_name='Habilidades relevantes')),
                ('descriptors', models.ManyToManyField(blank=True, to='world.worlddescriptor', verbose_name='Descriptores semánticos')),
            ],
            options={
                'verbose_name': 'Segmento de Mercado',
                'verbose_name_plural': 'Segmentos de Mercado',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalIDType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('regex_pattern', models.CharField(blank=True, max_length=200, verbose_name='Patrón de validación')),
                ('max_length', models.PositiveIntegerField(default=20, verbose_name='Longitud máxima')),
                ('min_length', models.PositiveIntegerField(default=1, verbose_name='Longitud mínima')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Organizacional',
                'verbose_name_plural': 'Tipos de Documentos Organizacionales',
                'ordering': ['country__name', 'display_order', 'name'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PersonalIDType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('regex_pattern', models.CharField(blank=True, help_text='Expresión regular para validar el formato', max_length=200, verbose_name='Patrón de validación')),
                ('max_length', models.PositiveIntegerField(default=20, verbose_name='Longitud máxima')),
                ('min_length', models.PositiveIntegerField(default=1, verbose_name='Longitud mínima')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Personal',
                'verbose_name_plural': 'Tipos de Documentos Personales',
                'ordering': ['country__name', 'display_order', 'name'],
                'unique_together': {('country', 'code')},
            },
        ),
    ]
