# Generated by Django 5.2.1 on 2025-09-24 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active'], name='world_acade_is_acti_c4ce00_idx'), models.Index(fields=['code'], name='world_acade_code_923d21_idx'), models.Index(fields=['name'], name='world_acade_name_fc39b6_idx'), models.Index(fields=['is_active', 'code'], name='world_acade_is_acti_fc8d92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código ISO3')),
                ('iso2_code', models.CharField(max_length=2, unique=True, verbose_name='Código ISO2')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('official_name', models.CharField(max_length=150, verbose_name='Nombre oficial')),
                ('phone_code', models.CharField(blank=True, max_length=5, verbose_name='Código telefónico')),
                ('currency_code', models.CharField(blank=True, max_length=3, verbose_name='Código de moneda')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Zona horaria principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='world_count_is_acti_71e539_idx'), models.Index(fields=['name'], name='world_count_name_862a03_idx'), models.Index(fields=['is_active', 'name'], name='world_count_is_acti_f21240_idx'), models.Index(fields=['timezone'], name='world_count_timezon_2b2220_idx'), models.Index(fields=['currency_code'], name='world_count_currenc_4e47aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='DescriptorFamily',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='world_descr_is_acti_53540d_idx'), models.Index(fields=['name'], name='world_descr_name_374adc_idx'), models.Index(fields=['is_active', 'name'], name='world_descr_is_acti_7f7d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunctionOrResponsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('typical_level', models.CharField(blank=True, choices=[('OP', 'Operativo'), ('TA', 'Táctico'), ('ST', 'Estratégico'), ('EX', 'Ejecutivo')], max_length=2, verbose_name='Nivel típico')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_functions', to='world.functionorresponsibility', verbose_name='Función padre')),
            ],
            options={
                'verbose_name': 'Función o Responsabilidad',
                'verbose_name_plural': 'Funciones o Responsabilidades',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_gende_is_acti_36f2a8_idx'), models.Index(fields=['display_order', 'name'], name='world_gende_display_eef035_idx'), models.Index(fields=['name'], name='world_gende_name_db87bf_idx'), models.Index(fields=['code'], name='world_gende_code_04519a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ciiu_code', models.CharField(blank=True, max_length=10, verbose_name='Código CIIU')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='world.industry', verbose_name='Industria padre')),
            ],
            options={
                'verbose_name': 'Industria',
                'verbose_name_plural': 'Industrias',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_marit_is_acti_ca6cb6_idx'), models.Index(fields=['display_order', 'name'], name='world_marit_display_9294d1_idx'), models.Index(fields=['name'], name='world_marit_name_f00d8e_idx'), models.Index(fields=['code'], name='world_marit_code_d9a0b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalIDType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('regex_pattern', models.CharField(blank=True, max_length=200, verbose_name='Patrón de validación')),
                ('max_length', models.PositiveIntegerField(default=20, verbose_name='Longitud máxima')),
                ('min_length', models.PositiveIntegerField(default=1, verbose_name='Longitud mínima')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Organizacional',
                'verbose_name_plural': 'Tipos de Documentos Organizacionales',
                'ordering': ['country__name', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ownership_type', models.CharField(choices=[('PVT', 'Privada'), ('PUB', 'Pública'), ('MIX', 'Mixta'), ('NGO', 'ONG/Sin fines de lucro')], default='PVT', max_length=3, verbose_name='Tipo de propiedad')),
                ('typical_size', models.CharField(blank=True, choices=[('MI', 'Microempresa'), ('SM', 'Pequeña'), ('ME', 'Mediana'), ('LA', 'Grande'), ('EN', 'Corporación')], max_length=2, verbose_name='Tamaño típico')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Organización',
                'verbose_name_plural': 'Tipos de Organización',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_organ_is_acti_495f35_idx'), models.Index(fields=['ownership_type'], name='world_organ_ownersh_c044c7_idx'), models.Index(fields=['typical_size'], name='world_organ_typical_0d5d42_idx'), models.Index(fields=['is_active', 'ownership_type'], name='world_organ_is_acti_9e25ff_idx'), models.Index(fields=['display_order', 'name'], name='world_organ_display_7720e5_idx'), models.Index(fields=['name'], name='world_organ_name_c202bd_idx'), models.Index(fields=['code'], name='world_organ_code_8f1347_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalIDType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('regex_pattern', models.CharField(blank=True, help_text='Expresión regular para validar el formato', max_length=200, verbose_name='Patrón de validación')),
                ('max_length', models.PositiveIntegerField(default=20, verbose_name='Longitud máxima')),
                ('min_length', models.PositiveIntegerField(default=1, verbose_name='Longitud mínima')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Personal',
                'verbose_name_plural': 'Tipos de Documentos Personales',
                'ordering': ['country__name', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(default='--', max_length=2, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='world_posit_is_acti_5f9ad7_idx'), models.Index(fields=['name'], name='world_posit_name_accccb_idx'), models.Index(fields=['code'], name='world_posit_code_ab2c85_idx'), models.Index(fields=['is_active', 'name'], name='world_posit_is_acti_18228a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('skill_type', models.CharField(choices=[('TE', 'Técnica'), ('SO', 'Blanda'), ('LE', 'Liderazgo'), ('AN', 'Analítica'), ('CR', 'Creativa')], default='TE', max_length=2, verbose_name='Tipo de habilidad')),
                ('typical_level_required', models.CharField(choices=[('BA', 'Básico'), ('IN', 'Intermedio'), ('AD', 'Avanzado'), ('EX', 'Experto')], default='IN', max_length=2, verbose_name='Nivel típico requerido')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['skill_type', 'display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_skill_is_acti_4d9126_idx'), models.Index(fields=['skill_type'], name='world_skill_skill_t_b4419f_idx'), models.Index(fields=['typical_level_required'], name='world_skill_typical_3795d6_idx'), models.Index(fields=['skill_type', 'display_order', 'name'], name='world_skill_skill_t_9a83c5_idx'), models.Index(fields=['is_active', 'skill_type'], name='world_skill_is_acti_7ce078_idx'), models.Index(fields=['name'], name='world_skill_name_7ad5bb_idx'), models.Index(fields=['code'], name='world_skill_code_32cdf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='world_tag_is_acti_a3193d_idx'), models.Index(fields=['name'], name='world_tag_name_470bea_idx'), models.Index(fields=['is_active', 'name'], name='world_tag_is_acti_480862_idx'), models.Index(fields=['created_at'], name='world_tag_created_f6668e_idx'), models.Index(fields=['updated_at'], name='world_tag_updated_bd6b35_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorldDescriptor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='world.descriptorfamily')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='world.worlddescriptor')),
            ],
            options={
                'ordering': ['family__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('segment_type', models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Consumer'), ('B2G', 'Business to Government')], default='B2B', max_length=3, verbose_name='Tipo de segmento')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility', verbose_name='Funciones típicas')),
                ('industries', models.ManyToManyField(blank=True, to='world.industry', verbose_name='Industrias relacionadas')),
                ('skills', models.ManyToManyField(blank=True, to='world.skill', verbose_name='Habilidades relevantes')),
                ('descriptors', models.ManyToManyField(blank=True, to='world.worlddescriptor', verbose_name='Descriptores semánticos')),
            ],
            options={
                'verbose_name': 'Segmento de Mercado',
                'verbose_name_plural': 'Segmentos de Mercado',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['is_active'], name='world_funct_is_acti_768612_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['parent'], name='world_funct_parent__fab445_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['is_active', 'parent'], name='world_funct_is_acti_c1e936_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['typical_level'], name='world_funct_typical_4dd002_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['display_order', 'name'], name='world_funct_display_4f37af_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['name'], name='world_funct_name_a680d4_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['code'], name='world_funct_code_0637da_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active'], name='world_indus_is_acti_d8310a_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['parent'], name='world_indus_parent__cbe840_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active', 'parent'], name='world_indus_is_acti_228f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['display_order', 'name'], name='world_indus_display_55e751_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['ciiu_code'], name='world_indus_ciiu_co_68d322_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['name'], name='world_indus_name_a6c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['code'], name='world_indus_code_0f7653_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['is_active'], name='world_organ_is_acti_3f9981_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['country'], name='world_organ_country_39460a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['is_active', 'country'], name='world_organ_is_acti_2af140_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['country', 'display_order', 'name'], name='world_organ_country_860b91_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['name'], name='world_organ_name_00ca80_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['code'], name='world_organ_code_a628d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationalidtype',
            unique_together={('country', 'code')},
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['is_active'], name='world_perso_is_acti_d83617_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['country'], name='world_perso_country_e08bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['is_active', 'country'], name='world_perso_is_acti_c405d1_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['country', 'display_order', 'name'], name='world_perso_country_68f566_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['name'], name='world_perso_name_f5ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['code'], name='world_perso_code_404415_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalidtype',
            unique_together={('country', 'code')},
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['is_active'], name='world_world_is_acti_eb4781_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family'], name='world_world_family__b7088b_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['parent'], name='world_world_parent__2d81e7_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['is_active', 'family'], name='world_world_is_acti_7067bc_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family', 'name'], name='world_world_family__35c9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family', 'parent'], name='world_world_family__200bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['name'], name='world_world_name_56f077_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['code'], name='world_world_code_fbf903_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worlddescriptor',
            unique_together={('family', 'name')},
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['is_active'], name='world_marke_is_acti_e876bd_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['segment_type'], name='world_marke_segment_8eb004_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['is_active', 'segment_type'], name='world_marke_is_acti_3a96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['display_order', 'name'], name='world_marke_display_c4b054_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['name'], name='world_marke_name_edef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['code'], name='world_marke_code_bc085f_idx'),
        ),
    ]
