# Generated by Django 5.2.1 on 2025-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicdegree',
            index=models.Index(fields=['is_active'], name='world_acade_is_acti_c4ce00_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdegree',
            index=models.Index(fields=['code'], name='world_acade_code_923d21_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdegree',
            index=models.Index(fields=['name'], name='world_acade_name_fc39b6_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdegree',
            index=models.Index(fields=['is_active', 'code'], name='world_acade_is_acti_fc8d92_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='world_count_is_acti_71e539_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='world_count_name_862a03_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active', 'name'], name='world_count_is_acti_f21240_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['timezone'], name='world_count_timezon_2b2220_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['currency_code'], name='world_count_currenc_4e47aa_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptorfamily',
            index=models.Index(fields=['is_active'], name='world_descr_is_acti_53540d_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptorfamily',
            index=models.Index(fields=['name'], name='world_descr_name_374adc_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptorfamily',
            index=models.Index(fields=['is_active', 'name'], name='world_descr_is_acti_7f7d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['is_active'], name='world_funct_is_acti_768612_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['parent'], name='world_funct_parent__fab445_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['is_active', 'parent'], name='world_funct_is_acti_c1e936_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['typical_level'], name='world_funct_typical_4dd002_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['display_order', 'name'], name='world_funct_display_4f37af_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['name'], name='world_funct_name_a680d4_idx'),
        ),
        migrations.AddIndex(
            model_name='functionorresponsibility',
            index=models.Index(fields=['code'], name='world_funct_code_0637da_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active'], name='world_indus_is_acti_d8310a_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['parent'], name='world_indus_parent__cbe840_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active', 'parent'], name='world_indus_is_acti_228f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['display_order', 'name'], name='world_indus_display_55e751_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['ciiu_code'], name='world_indus_ciiu_co_68d322_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['name'], name='world_indus_name_a6c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['code'], name='world_indus_code_0f7653_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['is_active'], name='world_marke_is_acti_e876bd_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['segment_type'], name='world_marke_segment_8eb004_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['is_active', 'segment_type'], name='world_marke_is_acti_3a96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['display_order', 'name'], name='world_marke_display_c4b054_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['name'], name='world_marke_name_edef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsegment',
            index=models.Index(fields=['code'], name='world_marke_code_bc085f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['is_active'], name='world_organ_is_acti_3f9981_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['country'], name='world_organ_country_39460a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['is_active', 'country'], name='world_organ_is_acti_2af140_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['country', 'display_order', 'name'], name='world_organ_country_860b91_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['name'], name='world_organ_name_00ca80_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalidtype',
            index=models.Index(fields=['code'], name='world_organ_code_a628d2_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['is_active'], name='world_organ_is_acti_495f35_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['ownership_type'], name='world_organ_ownersh_c044c7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['typical_size'], name='world_organ_typical_0d5d42_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['is_active', 'ownership_type'], name='world_organ_is_acti_9e25ff_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['display_order', 'name'], name='world_organ_display_7720e5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['name'], name='world_organ_name_c202bd_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtype',
            index=models.Index(fields=['code'], name='world_organ_code_8f1347_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['is_active'], name='world_perso_is_acti_d83617_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['country'], name='world_perso_country_e08bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['is_active', 'country'], name='world_perso_is_acti_c405d1_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['country', 'display_order', 'name'], name='world_perso_country_68f566_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['name'], name='world_perso_name_f5ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='personalidtype',
            index=models.Index(fields=['code'], name='world_perso_code_404415_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['is_active'], name='world_posit_is_acti_5f9ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['name'], name='world_posit_name_accccb_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['code'], name='world_posit_code_ab2c85_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['is_active', 'name'], name='world_posit_is_acti_18228a_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active'], name='world_skill_is_acti_4d9126_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['skill_type'], name='world_skill_skill_t_b4419f_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['typical_level_required'], name='world_skill_typical_3795d6_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['skill_type', 'display_order', 'name'], name='world_skill_skill_t_9a83c5_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active', 'skill_type'], name='world_skill_is_acti_7ce078_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='world_skill_name_7ad5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='world_skill_code_32cdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='world_tag_is_acti_a3193d_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='world_tag_name_470bea_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'name'], name='world_tag_is_acti_480862_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_at'], name='world_tag_created_f6668e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['updated_at'], name='world_tag_updated_bd6b35_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['is_active'], name='world_world_is_acti_eb4781_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family'], name='world_world_family__b7088b_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['parent'], name='world_world_parent__2d81e7_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['is_active', 'family'], name='world_world_is_acti_7067bc_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family', 'name'], name='world_world_family__35c9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['family', 'parent'], name='world_world_family__200bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['name'], name='world_world_name_56f077_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddescriptor',
            index=models.Index(fields=['code'], name='world_world_code_fbf903_idx'),
        ),
    ]
