# Generated by Django 5.2.1 on 2025-09-24 22:11

import json
import os
from django.db import migrations
from django.conf import settings


def populate_world_data(apps, schema_editor):
    """Populate world models with data from JSON files"""
    
    # Get the models
    Country = apps.get_model('world', 'Country')
    Industry = apps.get_model('world', 'Industry')
    FunctionOrResponsibility = apps.get_model('world', 'FunctionOrResponsibility')
    Position = apps.get_model('world', 'Position')
    
    # Get the data directory path
    data_dir = os.path.join(settings.BASE_DIR, 'world', 'data')
    
    # Load and populate countries
    countries_file = os.path.join(data_dir, 'countries.json')
    if os.path.exists(countries_file):
        with open(countries_file, 'r', encoding='utf-8') as f:
            countries_data = json.load(f)
            
        for country_data in countries_data.get('countries', []):
            Country.objects.get_or_create(
                iso3_code=country_data['iso3_code'],
                defaults={
                    'iso2_code': country_data.get('iso2_code', ''),
                    'name': country_data['short_name'],
                    'official_name': country_data['official_name'],
                    'phone_code': country_data.get('phone_code', ''),
                    'is_active': True
                }
            )
    
    # Load and populate industries
    industries_file = os.path.join(data_dir, 'industries.json')
    if os.path.exists(industries_file):
        with open(industries_file, 'r', encoding='utf-8') as f:
            industries_data = json.load(f)
            
        for industry_data in industries_data.get('industries', []):
            Industry.objects.get_or_create(
                code=industry_data['code'],
                defaults={
                    'name': industry_data['name'],
                    'description': f"Complexity Score: {industry_data.get('complexityScore', 'N/A')}",
                    'is_active': True
                }
            )
    
    # Load and populate functions
    functions_file = os.path.join(data_dir, 'functions.json')
    if os.path.exists(functions_file):
        with open(functions_file, 'r', encoding='utf-8') as f:
            functions_data = json.load(f)
            
        for function_data in functions_data.get('functions', []):
            FunctionOrResponsibility.objects.get_or_create(
                code=function_data['code'],
                defaults={
                    'name': function_data['name'],
                    'description': f"Relevance Score: {function_data.get('relevanceScore', 'N/A')}",
                    'is_active': True
                }
            )
    
    # Load and populate positions
    positions_file = os.path.join(data_dir, 'positions.json')
    if os.path.exists(positions_file):
        with open(positions_file, 'r', encoding='utf-8') as f:
            positions_data = json.load(f)
            
        for position_data in positions_data.get('positions', []):
            Position.objects.get_or_create(
                code=position_data['code'],
                defaults={
                    'name': position_data['name'],
                    'description': f"Authority Score: {position_data.get('authorityScore', 'N/A')}",
                    'is_active': True
                }
            )


def reverse_populate_world_data(apps, schema_editor):
    """Reverse the data population"""
    # Get the models
    Country = apps.get_model('world', 'Country')
    Industry = apps.get_model('world', 'Industry')
    FunctionOrResponsibility = apps.get_model('world', 'FunctionOrResponsibility')
    Position = apps.get_model('world', 'Position')
    
    # Clear the data
    Country.objects.all().delete()
    Industry.objects.all().delete()
    FunctionOrResponsibility.objects.all().delete()
    Position.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_world_data,
            reverse_populate_world_data
        ),
    ]
