# Generated by Django 5.2.1 on 2025-09-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
    ]
