# Generated by Django 5.2.1 on 2025-09-16 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_gende_is_acti_36f2a8_idx'), models.Index(fields=['display_order', 'name'], name='world_gende_display_eef035_idx'), models.Index(fields=['name'], name='world_gende_name_db87bf_idx'), models.Index(fields=['code'], name='world_gende_code_04519a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='world_marit_is_acti_ca6cb6_idx'), models.Index(fields=['display_order', 'name'], name='world_marit_display_9294d1_idx'), models.Index(fields=['name'], name='world_marit_name_f00d8e_idx'), models.Index(fields=['code'], name='world_marit_code_d9a0b5_idx')],
            },
        ),
    ]
