# Generated by Django 5.2.1 on 2025-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='included_products',
            field=models.ManyToManyField(blank=True, help_text='Otros productos incluidos conceptualmente dentro de este', related_name='bundled_in', to='products.product'),
        ),
    ]
