# Generated by Django 5.2.1 on 2025-06-05 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['division__name', 'name'], 'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='products_di_is_acti_e5ae0c_idx'), models.Index(fields=['name'], name='products_di_name_25ebdc_idx'), models.Index(fields=['code'], name='products_di_code_36e888_idx')],
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.division', verbose_name='División'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['division', 'is_active'], name='products_pr_divisio_b84c53_idx'),
        ),
    ]
