# Generated by Django 5.2.1 on 2025-06-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_options_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Página principal donde se presenta este producto', null=True, verbose_name='URL del producto'),
        ),
    ]
