# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_included_products'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_code_4c2607_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='products_pr_parent__84d628_idx',
        ),
    ]
