# Generated by Django 5.2.1 on 2025-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='included_products',
            field=models.ManyToManyField(blank=True, help_text='Otros productos incluidos conceptualmente dentro de este', related_name='included_in_products', to='products.product'),
        ),
    ]
