"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,192.168.97.4,backend.proyecto-opensource.orb.local,frontend.proyecto-opensource.orb.local').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_redis',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'users',
    'world',
    'products',
    'entities',
    'interactions',
    'our_institution',
    'offers',
    'campaigns',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Render database configuration
import os
from urllib.parse import urlparse

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Parse DATABASE_URL for Render deployment
    db_info = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_info.path[1:],
            'USER': db_info.username,
            'PASSWORD': db_info.password,
            'HOST': db_info.hostname,
            'PORT': db_info.port,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
else:
    # Local development configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DATABASE_NAME', default='mydatabase'),
            'USER': config('DATABASE_USER', default='myuser'),
            'PASSWORD': config('DATABASE_PASSWORD', default='mypassword'),
            'HOST': config('DATABASE_HOST', default='localhost'),
            'PORT': config('DATABASE_PORT', default='5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DEFAULT_AUTO_FIELD = 'backend.fields.UUIDAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:3000",  # Nuxt.js development server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite development server (fallback)
    "http://127.0.0.1:5173",
    "https://backboneos-frontend.onrender.com",  # Render frontend
    "https://backboneos.com",  # Custom domain
    "https://backend.proyecto-opensource.orb.local",  # Local development domain
    "https://frontend.proyecto-opensource.orb.local",  # Local frontend domain
]).split(',') if isinstance(config('CORS_ALLOWED_ORIGINS', default=None), str) else [
    "http://localhost:3000",  # Nuxt.js development server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite development server (fallback)
    "http://127.0.0.1:5173",
    "https://backboneos-frontend.onrender.com",  # Render frontend
    "https://backboneos.com",  # Custom domain
    "https://backend.proyecto-opensource.orb.local",  # Local development domain
    "https://frontend.proyecto-opensource.orb.local",  # Local frontend domain
]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default=[
    "https://backboneos-backend.onrender.com",
    "https://backboneos-frontend.onrender.com",
    "https://backboneos.com",
    "https://backend.proyecto-opensource.orb.local",
    "https://frontend.proyecto-opensource.orb.local",
]).split(',') if isinstance(config('CSRF_TRUSTED_ORIGINS', default=None), str) else [
    "https://backboneos-backend.onrender.com",
    "https://backboneos-frontend.onrender.com",
    "https://backboneos.com",
    "https://backend.proyecto-opensource.orb.local",
    "https://frontend.proyecto-opensource.orb.local",
]

# Security Settings for Production
if not DEBUG:
    # HTTPS Settings - Disable SSL redirect on Render since it's already behind HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    
    # Cookie Security
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    
    # Browser Security
    SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings for HTTPS with self-signed certificates
    # Allow CSRF cookies to work with self-signed certificates
    CSRF_COOKIE_SECURE = False  # Allow CSRF cookies over HTTP/HTTPS in development
    SESSION_COOKIE_SECURE = False  # Allow session cookies over HTTP/HTTPS in development
    CSRF_COOKIE_SAMESITE = 'Lax'  # More permissive for development
    SESSION_COOKIE_SAMESITE = 'Lax'  # More permissive for development
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token in development
    CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF

# Add production origins from environment variables
PRODUCTION_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='').split(',')
if PRODUCTION_ORIGINS and PRODUCTION_ORIGINS[0]:  # Check if not empty
    CORS_ALLOWED_ORIGINS.extend(PRODUCTION_ORIGINS)

CORS_ALLOW_CREDENTIALS = True

# Security settings based on environment
if DEBUG:
    # Development settings - more permissive
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_ALL_HEADERS = True
else:
    # Production settings - more restrictive
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]



# =============================================================================
# CONFIGURACIÓN DE REDIS Y CACHÉ
# =============================================================================
# Redis se utiliza para:
# - Caché de aplicación (mejorar rendimiento de queries y vistas)
# - Almacenamiento de sesiones de usuario
# - Cache de tokens JWT y autenticación
# Configuración optimizada para desarrollo y producción
# Ver documentación completa en: docs/REDIS.md

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("DJANGO_REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "IGNORE_EXCEPTIONS": True,  # Evita errores si Redis no está disponible
        },
        "KEY_PREFIX": "backend_cache",  # Prefijo para evitar colisiones
        "TIMEOUT": 300,  # Timeout por defecto de 5 minutos
    }
}

# =============================================================================
# CONFIGURACIÓN DE SESIONES CON REDIS
# =============================================================================
# Utiliza Redis como backend de sesiones para mejor rendimiento y escalabilidad
# Fallback automático a base de datos si Redis no está disponible

if config("USE_REDIS_SESSIONS", default=True, cast=bool):
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = 86400  # 24 horas
    SESSION_SAVE_EVERY_REQUEST = False  # Solo guarda si se modifica
else:
    # Fallback a database sessions
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Configuración de cookies de sesión
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS en producción
SESSION_COOKIE_HTTPONLY = True  # Previene XSS
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF



# =============================================================================
# CONFIGURACIÓN DE CELERY
# =============================================================================
# Render Redis configuration
REDIS_URL = config('REDIS_URL', default=None)

if REDIS_URL:
    # Use Render Redis URL
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    
    # Update cache configuration for Render
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {"max_connections": 50},
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': "backend_cache",
            'TIMEOUT': 300,
        }
    }
    
    # Use Redis for sessions on Render
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Local development configuration
    CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
    CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/2")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Celery Beat specific settings
CELERY_BEAT_SCHEDULE_FILENAME = '/tmp/celerybeat-schedule'
CELERY_BEAT_MAX_LOOP_INTERVAL = 5  # seconds



# # Configuración de seguridad adicional
# SECURE_BROWSER_XSS_FILTER = True  # Activa el filtro XSS del navegador
# SECURE_CONTENT_TYPE_NOSNIFF = True  # Previene el sniffing de contenido
# SECURE_SSL_REDIRECT = not DEBUG  # Redirige a HTTPS en producción
# # Configuración de CSRF
# CSRF_COOKIE_SECURE = not DEBUG  # HTTPS en producción
# CSRF_COOKIE_HTTPONLY = True  # Previene XSS
# CSRF_COOKIE_SAMESITE = 'Lax'  # Protección CSRF
# # Configuración de seguridad de la cabecera HTTP Strict Transport Security (HSTS)
# SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0  # Habilita HSTS en producción
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Aplica HSTS a subdominios
# SECURE_HSTS_PRELOAD = True  # Permite el preload de HSTS
# # Configuración de logging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': config('DJANGO_LOG_LEVEL', default='INFO'),
#         },
#     },
# }



# Sistema de logging de actividad
LOG_USER_ACTIVITY = config("LOG_USER_ACTIVITY", default=False, cast=bool)  # Si se registra la actividad del usuario
# USER_ACTIVITY_BACKEND = config("USER_ACTIVITY_BACKEND", default="mongodb")  # 'mongodb' or 'dynamodb'
# USE_CELERY = config("USE_CELERY", default=True, cast=bool)  # Si se usa Celery para logging asíncrono

# # Configuración para MongoDB
# MONGODB_URI = config("MONGODB_URI")
# MONGODB_DB_NAME = "backbone_logs"

# # Configuración para DynamoDB (si aplica)
# AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
# AWS_DYNAMODB_REGION = "us-west-2"
# AWS_DYNAMODB_ENDPOINT = config("AWS_DYNAMODB_ENDPOINT", None)  # opcional
# AWS_USER_ACTIVITY_TABLE = "UserActivityLogs"

# =============================================================================
# SENTRY CONFIGURATION
# =============================================================================
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

SENTRY_DSN = config('SENTRY_DSN', default=None)

if SENTRY_DSN and not DEBUG:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        # Performance monitoring
        traces_sample_rate=0.1,  # 10% of transactions
        # Send errors to Sentry
        send_default_pii=True,
        # Environment
        environment='production',
        # Additional options to handle Python 3.13 compatibility
        max_breadcrumbs=50,
        attach_stacktrace=True,
        # Disable problematic features that cause pickle errors
        before_send=lambda event, hint: event if not any(
            'FrameLocalsProxy' in str(error.get('value', '')) 
            for error in event.get('exception', {}).get('values', [])
        ) else None,
    )

# =============================================================================
# CELERY PRODUCTION SETTINGS
# =============================================================================
# Celery result expiration to prevent Redis memory issues
CELERY_RESULT_EXPIRES = config('CELERY_RESULT_EXPIRES', default=3600, cast=int)  # 1 hour

# Task routing for better performance
CELERY_TASK_ROUTES = {
    'users.*': {'queue': 'users'},
    'products.*': {'queue': 'products'},
    'entities.*': {'queue': 'entities'},
    'interactions.*': {'queue': 'interactions'},
    'campaigns.*': {'queue': 'campaigns'},
    'offers.*': {'queue': 'offers'},
}

# Task serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000