# Generated by Django 5.2.1 on 2025-06-12 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0002_alter_interaction_jtbd_stage'),
        ('our_institution', '0001_initial'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(blank=True, to='interactions.channel')),
                ('descriptors', models.ManyToManyField(blank=True, to='world.worlddescriptor')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_institution.division')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcampaigns', to='campaigns.campaign')),
                ('related_functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility')),
                ('related_industries', models.ManyToManyField(blank=True, to='world.industry')),
                ('tags', models.ManyToManyField(blank=True, to='world.tag')),
                ('target_segments', models.ManyToManyField(blank=True, to='world.marketsegment')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_institution.team')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('expected_conversions', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('touchpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.touchpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_c_is_acti_7a198a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='campaigns_c_start_d_38d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='campaigns_c_end_dat_0a825a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntouchpoint',
            unique_together={('campaign', 'touchpoint')},
        ),
    ]
