# Generated by Django 5.2.1 on 2025-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.CharField(blank=True, choices=[('affinity', 'Afinidad'), ('category', 'Categoría'), ('product', 'Producto'), ('brand', 'Marca')], max_length=20, null=True, verbose_name='Tipo de contenido comunicacional'),
        ),
    ]
