# Generated by Django 5.2.1 on 2025-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('interactions', '0001_move_medium_to_touchpoint_and_rename_touchpointclass'),
        ('offers', '0001_initial'),
        ('our_institution', '0001_initial'),
        ('products', '0002_alter_product_included_products'),
        ('world', '0002_populate_world_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['content_type'], name='campaigns_c_content_33054c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['division'], name='campaigns_c_divisio_226b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['team'], name='campaigns_c_team_id_3b8e59_idx'),
        ),
    ]
