# Generated by Django 5.2.1 on 2025-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_indexes_for_product_integration'),
        ('interactions', '0001_move_medium_to_touchpoint_and_rename_touchpointclass'),
        ('offers', '0001_initial'),
        ('our_institution', '0001_initial'),
        ('products', '0002_alter_product_included_products'),
        ('world', '0002_populate_world_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active', 'start_date'], name='campaigns_c_is_acti_f4a960_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active', 'content_type'], name='campaigns_c_is_acti_44dbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['division', 'is_active'], name='campaigns_c_divisio_40f210_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['funnel_stage', 'is_active'], name='campaigns_c_funnel__b8cbbc_idx'),
        ),
    ]
