# Generated by Django 5.2.1 on 2025-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_content_type'),
        ('interactions', '0002_alter_interaction_jtbd_stage'),
        ('our_institution', '0001_initial'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='funnel_stage',
            field=models.CharField(blank=True, choices=[('see', 'Ver'), ('think', 'Pensar'), ('do', 'Hacer'), ('care', 'Cuidar'), ('any', 'Cualquiera')], default='any', help_text='Etapa del embudo de ventas para la cual está diseñada esta campaña', max_length=50),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['funnel_stage'], name='campaigns_c_funnel__a2a4ac_idx'),
        ),
    ]
