# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_divisio_226b7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_team_id_3b8e59_idx',
        ),
    ]
