# Generated by Django 5.2.1 on 2025-09-20 23:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0006_convert_gender_marital_status_to_foreign_keys'),
        ('interactions', '0005_add_touchpoint_is_active_index'),
        ('offers', '0001_initial'),
        ('products', '0004_add_included_products'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('web', 'Web'), ('email', 'Correo'), ('call', 'Llamada'), ('event', 'Evento'), ('referral', 'Referido'), ('other', 'Otro')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fuente de origen',
                'verbose_name_plural': 'Fuentes de origen',
                'ordering': ['group', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SalesState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(help_text='Identificador único para ordenamiento y comparación.', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text='Código único para referencia rápida, sin espacios ni caracteres especiales.', unique=True)),
                ('is_terminal', models.BooleanField(default=False)),
                ('requires_attention', models.BooleanField(default=False)),
                ('color', models.CharField(default='default', max_length=20)),
            ],
            options={
                'verbose_name': 'estado de oportunidad',
                'verbose_name_plural': 'estados de oportunidad',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('filter_stage', models.CharField(blank=True, choices=[('new', 'Nuevo'), ('interested', 'Interesado'), ('evaluating', 'Evaluando'), ('ready', 'Listo para decidir'), ('won', 'Convertido'), ('lost', 'Perdido')], max_length=20)),
                ('filter_probability_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('filter_probability_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Reglas dinámicas de filtrado para esta lista.')),
                ('build_in_background', models.BooleanField(default=True)),
                ('building_task_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('filter_tags', models.ManyToManyField(blank=True, to='users.usertag')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.productoffering')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Correo'), ('call', 'Llamada'), ('event', 'Evento'), ('referral', 'Referido'), ('other', 'Otro')], default='web', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'Nuevo'), ('interested', 'Interesado'), ('evaluating', 'Evaluando'), ('ready', 'Listo para decidir'), ('won', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('expected_closing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.channel')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.productoffering')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunities', to='products.product')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salessource')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesstate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('person', 'organization', 'offering')},
            },
        ),
        migrations.CreateModel(
            name='SalesSession',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.interaction')),
                ('contacted_via', models.PositiveSmallIntegerField(choices=[(0, 'Desconocido'), (10, 'Correo electrónico'), (20, 'Otro medio'), (30, 'Mensaje de texto'), (35, 'WhatsApp'), (40, 'Teléfono o llamada de audio'), (60, 'Video llamada'), (80, 'Vino al campus'), (100, 'Fuera del campus')], default=10, verbose_name='medio')),
                ('initiated_by', models.PositiveSmallIntegerField(choices=[(0, 'Cualquiera'), (1, 'Representante'), (2, 'Cliente')], default=0, verbose_name='iniciado por')),
                ('how_long', models.DurationField(blank=True, null=True)),
                ('lead_state', models.SmallIntegerField(blank=True, null=True)),
                ('progress', models.SmallIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('interested', 'Interesado'), ('not_interested', 'No interesado'), ('follow_up', 'Requiere seguimiento'), ('converted', 'Convertido'), ('no_show', 'No se presentó')], default='follow_up', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sessions', to='sales.salesopportunity')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
            bases=('interactions.interaction',),
        ),
        migrations.CreateModel(
            name='TaggedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_tags', to='sales.salesopportunity')),
                ('tags', models.ManyToManyField(to='users.usertag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAcquisition',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.interaction')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('payment_modality', models.CharField(choices=[('cash', 'Contado'), ('installments', 'Cuotas'), ('letter', 'Carta por cobrar')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='offers.productoffering')),
            ],
            options={
                'verbose_name': 'Adquisición de Producto',
                'verbose_name_plural': 'Adquisiciones de Productos',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['offering'], name='sales_produ_offerin_42e581_idx'), models.Index(fields=['price_paid'], name='sales_produ_price_p_f24781_idx'), models.Index(fields=['payment_modality'], name='sales_produ_payment_b45c30_idx')],
            },
            bases=('interactions.interaction',),
        ),
    ]
