# Generated by Django 5.2.1 on 2025-09-25 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_move_medium_to_touchpoint_and_rename_touchpointclass'),
        ('our_institution', '0001_initial'),
        ('products', '0002_alter_product_included_products'),
        ('world', '0002_populate_world_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duración de la suscripción en días (si aplica)', null=True)),
                ('landing_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('channels', models.ManyToManyField(blank=True, help_text='Canales permitidos para esta oferta', to='interactions.channel')),
                ('descriptors', models.ManyToManyField(blank=True, to='world.worlddescriptor')),
                ('products', models.ManyToManyField(blank=True, help_text='Productos ofrecidos en esta oferta comercial', related_name='offerings', to='products.product')),
                ('related_functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility')),
                ('related_industries', models.ManyToManyField(blank=True, to='world.industry')),
                ('seats', models.ManyToManyField(blank=True, to='our_institution.seat')),
                ('tags', models.ManyToManyField(blank=True, to='world.tag')),
                ('target_segments', models.ManyToManyField(blank=True, to='world.marketsegment')),
            ],
            options={
                'ordering': ['-valid_from', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='offers_prod_is_acti_d7ddd4_idx'), models.Index(fields=['valid_from'], name='offers_prod_valid_f_c54203_idx'), models.Index(fields=['valid_until'], name='offers_prod_valid_u_6501dc_idx'), models.Index(fields=['currency_code'], name='offers_prod_currenc_755279_idx')],
            },
        ),
    ]
