# Generated by Django 5.2.1 on 2025-09-18 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouchpointMappingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connector_type', models.CharField(help_text="Type of connector (e.g., 'web', 'email', 'whatsapp')", max_length=50)),
                ('source_identifier', models.CharField(blank=True, help_text='Specific source identifier (e.g., website URL, email domain)', max_length=200)),
                ('event_code', models.CharField(help_text="Event code to match (e.g., 'web.page_read', 'email.open')", max_length=100)),
                ('touchpoint_code', models.CharField(help_text="Touchpoint code to create (e.g., 'web.lead_form')", max_length=100)),
                ('touchpoint_label', models.CharField(blank=True, help_text='Human-friendly label for the touchpoint', max_length=200)),
                ('channel_code', models.CharField(blank=True, help_text="Channel code override (e.g., 'web', 'email')", max_length=50)),
                ('medium_code', models.CharField(blank=True, help_text="Medium code override (e.g., 'organic', 'paid', 'referral')", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata to include in the touchpoint')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Rule priority (higher = more specific)')),
            ],
            options={
                'verbose_name': 'Touchpoint Mapping Rule',
                'verbose_name_plural': 'Touchpoint Mapping Rules',
                'ordering': ['-priority', 'connector_type', 'event_code'],
                'indexes': [models.Index(fields=['connector_type', 'event_code'], name='connectors__connect_6a658c_idx'), models.Index(fields=['source_identifier', 'event_code'], name='connectors__source__2d0f4a_idx'), models.Index(fields=['priority'], name='connectors__priorit_db55ba_idx'), models.Index(fields=['is_active'], name='connectors__is_acti_891736_idx')],
                'unique_together': {('connector_type', 'source_identifier', 'event_code')},
            },
        ),
    ]
