# Generated by Django 5.2.1 on 2025-10-06 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connector_type', models.CharField(db_index=True, help_text="Type of connector (e.g., 'web', 'email', 'whatsapp')", max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text="Type of event (e.g., 'page_view', 'email_open', 'message_received')", max_length=100)),
                ('source_identifier', models.CharField(blank=True, help_text='Source identifier (e.g., website URL, email domain)', max_length=200)),
                ('raw_payload', models.JSONField(help_text='Complete raw event data as received')),
                ('status', models.CharField(choices=[('pending', 'Pending Retry'), ('processing', 'Currently Processing'), ('success', 'Successfully Processed'), ('failed', 'Failed (Will Retry)'), ('abandoned', 'Abandoned (Max Retries Exceeded)')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Latest error message')),
                ('error_trace', models.TextField(blank=True, help_text='Full stack trace of the error')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('first_failed_at', models.DateTimeField(auto_now_add=True, help_text='When this event first failed')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Last retry attempt timestamp', null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='Scheduled next retry time (exponential backoff)', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When successfully processed', null=True)),
                ('interaction_ids', models.JSONField(blank=True, default=list, help_text='IDs of interactions created when successfully processed')),
            ],
            options={
                'verbose_name': 'Failed Event',
                'verbose_name_plural': 'Failed Events',
                'ordering': ['-first_failed_at'],
                'indexes': [models.Index(fields=['connector_type', 'status'], name='connectors__connect_879d81_idx'), models.Index(fields=['status', 'next_retry_at'], name='connectors__status_27674c_idx'), models.Index(fields=['event_type', 'status'], name='connectors__event_t_6d42bd_idx'), models.Index(fields=['is_active', 'status'], name='connectors__is_acti_e7dc27_idx')],
            },
        ),
    ]
