# Generated by Django 5.2.1 on 2025-09-24 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0002_populate_world_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=190)),
                ('legal_name', models.CharField(blank=True, max_length=190)),
                ('id_number', models.CharField(max_length=20)),
                ('main_address', models.CharField(blank=True, max_length=190)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.organizationalidtype')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.industry')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.organizationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('first_name', models.CharField(blank=True, max_length=63)),
                ('middle_name', models.CharField(blank=True, max_length=63)),
                ('last_name', models.CharField(blank=True, max_length=63)),
                ('second_last_name', models.CharField(blank=True, max_length=63)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='public/profiles/')),
                ('country_of_nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.gender')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.personalidtype')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.maritalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('accepts_privacy_policy', models.BooleanField(default=False)),
                ('allows_marketing', models.BooleanField(default=False)),
                ('preferred_contact_medium', models.CharField(choices=[('EM', 'Email'), ('TX', 'Texto'), ('PH', 'Teléfono'), ('VD', 'Videollamada'), ('IP', 'Presencial'), ('NN', 'Desconocido')], default='NN', max_length=2)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.academicdegree')),
                ('functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility')),
                ('industries', models.ManyToManyField(blank=True, to='world.industry')),
                ('skills', models.ManyToManyField(blank=True, to='world.skill')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.person')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('address_extra', models.CharField(blank=True, max_length=100, verbose_name='Información adicional')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('region_or_state', models.CharField(blank=True, max_length=100, verbose_name='Región o Estado')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Dirección principal')),
                ('use_for_billing', models.BooleanField(default=False, verbose_name='Usar para facturación')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country', verbose_name='País')),
                ('owner_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.organization', verbose_name='Organización propietaria')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.person', verbose_name='Persona propietaria')),
            ],
            options={
                'verbose_name': 'Dirección Física',
                'verbose_name_plural': 'Direcciones Físicas',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='entities_or_name_fe1893_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['legal_name'], name='entities_or_legal_n_685638_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='entities_or_org_typ_80283b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='entities_or_industr_21663d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country'], name='entities_or_country_7b6108_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['id_type'], name='entities_or_id_type_a7ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['id_type', 'id_number'], name='entities_or_id_type_fc6ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'org_type'], name='entities_or_is_acti_b123c6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'industry'], name='entities_or_is_acti_bb15c2_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'country'], name='entities_or_is_acti_cb775b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type', 'industry'], name='entities_or_org_typ_a2971a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country', 'industry'], name='entities_or_country_1d1269_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='entities_or_is_acti_9a5bcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('id_type', 'id_number')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='entities_pe_first_n_60102d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='entities_pe_gender__522465_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['marital_status'], name='entities_pe_marital_32e17d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['birthday'], name='entities_pe_birthda_a6e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_of_nationality'], name='entities_pe_country_f25dae_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id_type'], name='entities_pe_id_type_3da697_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id_type', 'id_number'], name='entities_pe_id_type_2878bb_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='entities_pe_is_acti_911fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'country_of_nationality'], name='entities_pe_is_acti_b72a60_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'gender'], name='entities_pe_is_acti_11ce92_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'marital_status'], name='entities_pe_is_acti_8e6b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'birthday'], name='entities_pe_is_acti_e3ff5c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender', 'country_of_nationality'], name='entities_pe_gender__633dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['marital_status', 'gender'], name='entities_pe_marital_2f7a66_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='entities_pe_created_0a4745_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['updated_at'], name='entities_pe_updated_ab13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'created_at'], name='entities_pe_is_acti_4ade97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('id_type', 'id_number')},
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['person'], name='entities_in_person__0539c0_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree'], name='entities_in_academi_a552a4_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['preferred_contact_medium'], name='entities_in_preferr_9816d2_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['accepts_privacy_policy'], name='entities_in_accepts_b19e33_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['allows_marketing'], name='entities_in_allows__68372a_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active'], name='entities_in_is_acti_b02d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'academic_degree'], name='entities_in_is_acti_4adda3_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'allows_marketing'], name='entities_in_is_acti_d24d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'preferred_contact_medium'], name='entities_in_is_acti_e8f196_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'accepts_privacy_policy'], name='entities_in_is_acti_bbedff_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree', 'allows_marketing'], name='entities_in_academi_a683cb_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['preferred_contact_medium', 'allows_marketing'], name='entities_in_preferr_075622_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['accepts_privacy_policy', 'allows_marketing'], name='entities_in_accepts_9bf09a_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['person', 'is_active'], name='entities_in_person__5d090e_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree', 'preferred_contact_medium'], name='entities_in_academi_e3d4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person'], name='entities_co_person__cd31a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization'], name='entities_co_organiz_aa8f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_primary'], name='entities_co_is_prim_fadc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['verified'], name='entities_co_verifie_f4137a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email'], name='entities_co_email_bfb79d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone'], name='entities_co_phone_eb486d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active'], name='entities_co_is_acti_3b0512_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'is_primary'], name='entities_co_person__9aedfa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'is_primary'], name='entities_co_organiz_c6bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'is_active'], name='entities_co_person__5c09a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'is_active'], name='entities_co_organiz_99f24b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active', 'is_primary'], name='entities_co_is_acti_00acbc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active', 'verified'], name='entities_co_is_acti_de17d9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_primary', 'verified'], name='entities_co_is_prim_d2fc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email', 'verified'], name='entities_co_email_9d398b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone', 'verified'], name='entities_co_phone_1b4c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email', 'is_active'], name='entities_co_email_f17898_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone', 'is_active'], name='entities_co_phone_3a57f6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'verified'], name='entities_co_person__91f8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'verified'], name='entities_co_organiz_5cf083_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactdetail',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('organization__isnull', False), _connector='OR'), name='contact_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='contactdetail',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('organization__isnull', False), _negated=True), name='contact_single_owner_only'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_primary'], name='entities_ph_is_prim_a5beeb_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['use_for_billing'], name='entities_ph_use_for_d0c776_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person'], name='entities_ph_owner_p_e08017_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org'], name='entities_ph_owner_o_96ce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['country'], name='entities_ph_country_73c436_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['city'], name='entities_ph_city_b86ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['country', 'city'], name='entities_ph_country_1dbc15_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['region_or_state', 'city'], name='entities_ph_region__0956bd_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_active', 'is_primary'], name='entities_ph_is_acti_3b570d_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_active', 'use_for_billing'], name='entities_ph_is_acti_722d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person', 'is_primary'], name='entities_ph_owner_p_cb9079_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org', 'is_primary'], name='entities_ph_owner_o_82752f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person', 'is_active'], name='entities_ph_owner_p_f4dfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org', 'is_active'], name='entities_ph_owner_o_2aeb8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicaladdress',
            constraint=models.CheckConstraint(condition=models.Q(('owner_person__isnull', False), ('owner_org__isnull', False), _connector='OR'), name='address_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='physicaladdress',
            constraint=models.CheckConstraint(condition=models.Q(('owner_person__isnull', False), ('owner_org__isnull', False), _negated=True), name='address_single_owner_only'),
        ),
    ]
