# Generated by Django 5.2.1 on 2025-06-05 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=190)),
                ('legal_name', models.CharField(blank=True, max_length=190)),
                ('id_number', models.CharField(max_length=20)),
                ('main_address', models.CharField(blank=True, max_length=190)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.organizationalidtype')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.industry')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.organizationtype')),
            ],
            options={
                'unique_together': {('id_type', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('first_name', models.CharField(blank=True, max_length=63)),
                ('middle_name', models.CharField(blank=True, max_length=63)),
                ('fathers_name', models.CharField(blank=True, max_length=63)),
                ('mothers_name', models.CharField(blank=True, max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('UD', 'No definido')], default='UD', max_length=2)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('SG', 'Soltero'), ('MR', 'Casado'), ('DV', 'Divorciado'), ('SP', 'Separado'), ('WD', 'Viudo'), ('CH', 'Conviviente'), ('UD', 'No definido')], default='UD', max_length=2)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='public/profiles/')),
                ('country_of_nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.personalidtype')),
            ],
            options={
                'unique_together': {('id_type', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('accepts_privacy_policy', models.BooleanField(default=False)),
                ('allows_marketing', models.BooleanField(default=False)),
                ('preferred_contact_medium', models.CharField(choices=[('EM', 'Email'), ('TX', 'Texto'), ('PH', 'Teléfono'), ('VD', 'Videollamada'), ('IP', 'Presencial'), ('NN', 'Desconocido')], default='NN', max_length=2)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.academicdegree')),
                ('functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility')),
                ('industries', models.ManyToManyField(blank=True, to='world.industry')),
                ('skills', models.ManyToManyField(blank=True, to='world.skill')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('address', models.CharField(max_length=200)),
                ('address_extra', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region_or_state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('use_for_billing', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country')),
                ('owner_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.organization')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.person')),
            ],
            options={
                'indexes': [models.Index(fields=['is_primary', 'verified'], name='entities_co_is_prim_d2fc3e_idx')],
            },
        ),
    ]
