# Generated by Django 5.2.1 on 2025-06-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicaladdress',
            options={'verbose_name': 'Dirección Física', 'verbose_name_plural': 'Direcciones Físicas'},
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='address_extra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Información adicional'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Dirección principal'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.organization', verbose_name='Organización propietaria'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.person', verbose_name='Persona propietaria'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='region_or_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región o Estado'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='use_for_billing',
            field=models.BooleanField(default=False, verbose_name='Usar para facturación'),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_primary'], name='entities_ph_is_prim_a5beeb_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['use_for_billing'], name='entities_ph_use_for_d0c776_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person'], name='entities_ph_owner_p_e08017_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org'], name='entities_ph_owner_o_96ce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['country'], name='entities_ph_country_73c436_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['city'], name='entities_ph_city_b86ac0_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicaladdress',
            constraint=models.CheckConstraint(condition=models.Q(('owner_person__isnull', False), ('owner_org__isnull', False), _connector='OR'), name='address_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='physicaladdress',
            constraint=models.CheckConstraint(condition=models.Q(('owner_person__isnull', False), ('owner_org__isnull', False), _negated=True), name='address_single_owner_only'),
        ),
    ]
