# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactdetail',
            name='entities_co_person__cd31a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactdetail',
            name='entities_co_organiz_aa8f6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactdetail',
            name='entities_co_is_prim_d2fc3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='individualprofile',
            name='entities_in_person__0539c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='individualprofile',
            name='entities_in_academi_a552a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='entities_or_org_typ_80283b_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='entities_or_industr_21663d_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='entities_or_country_7b6108_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='entities_or_id_type_a7ca6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='entities_pe_gender__522465_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='entities_pe_marital_32e17d_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='entities_pe_country_f25dae_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='entities_pe_id_type_3da697_idx',
        ),
    ]
