# Generated by Django 5.2.1 on 2025-06-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_physicaladdress_options_and_more'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person'], name='entities_co_person__cd31a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email'], name='entities_co_email_bfb79d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone'], name='entities_co_phone_eb486d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'is_primary'], name='entities_co_person__9aedfa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'is_active'], name='entities_co_person__5c09a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active', 'is_primary'], name='entities_co_is_acti_00acbc_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['person'], name='entities_in_person__0539c0_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree'], name='entities_in_academi_a552a4_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['preferred_contact_medium'], name='entities_in_preferr_9816d2_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['accepts_privacy_policy'], name='entities_in_accepts_b19e33_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['allows_marketing'], name='entities_in_allows__68372a_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'academic_degree'], name='entities_in_is_acti_4adda3_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'allows_marketing'], name='entities_in_is_acti_d24d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'preferred_contact_medium'], name='entities_in_is_acti_e8f196_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree', 'allows_marketing'], name='entities_in_academi_a683cb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='entities_or_name_fe1893_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['legal_name'], name='entities_or_legal_n_685638_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='entities_or_org_typ_80283b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='entities_or_industr_21663d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country'], name='entities_or_country_7b6108_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['id_type'], name='entities_or_id_type_a7ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['id_type', 'id_number'], name='entities_or_id_type_fc6ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'org_type'], name='entities_or_is_acti_b123c6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'industry'], name='entities_or_is_acti_bb15c2_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'country'], name='entities_or_is_acti_cb775b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type', 'industry'], name='entities_or_org_typ_a2971a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country', 'industry'], name='entities_or_country_1d1269_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='entities_or_is_acti_9a5bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'fathers_name'], name='entities_pe_first_n_a92eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='entities_pe_gender_89874f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['marital_status'], name='entities_pe_marital_e1e6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['birthday'], name='entities_pe_birthda_a6e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_of_nationality'], name='entities_pe_country_f25dae_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id_type'], name='entities_pe_id_type_3da697_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id_type', 'id_number'], name='entities_pe_id_type_2878bb_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='entities_pe_is_acti_911fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'country_of_nationality'], name='entities_pe_is_acti_b72a60_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'gender'], name='entities_pe_is_acti_f517d0_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['country', 'city'], name='entities_ph_country_1dbc15_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['region_or_state', 'city'], name='entities_ph_region__0956bd_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_active', 'is_primary'], name='entities_ph_is_acti_3b570d_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['is_active', 'use_for_billing'], name='entities_ph_is_acti_722d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person', 'is_primary'], name='entities_ph_owner_p_cb9079_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org', 'is_primary'], name='entities_ph_owner_o_82752f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_person', 'is_active'], name='entities_ph_owner_p_f4dfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='physicaladdress',
            index=models.Index(fields=['owner_org', 'is_active'], name='entities_ph_owner_o_2aeb8e_idx'),
        ),
    ]
