# Generated by Django 5.2.1 on 2025-06-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_add_optimized_indexes'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.organization'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.person'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization'], name='entities_co_organiz_aa8f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_primary'], name='entities_co_is_prim_fadc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['verified'], name='entities_co_verifie_f4137a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active'], name='entities_co_is_acti_3b0512_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'is_primary'], name='entities_co_organiz_c6bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'is_active'], name='entities_co_organiz_99f24b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['is_active', 'verified'], name='entities_co_is_acti_de17d9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email', 'verified'], name='entities_co_email_9d398b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone', 'verified'], name='entities_co_phone_1b4c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['email', 'is_active'], name='entities_co_email_f17898_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['phone', 'is_active'], name='entities_co_phone_3a57f6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['person', 'verified'], name='entities_co_person__91f8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='contactdetail',
            index=models.Index(fields=['organization', 'verified'], name='entities_co_organiz_5cf083_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active'], name='entities_in_is_acti_b02d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['is_active', 'accepts_privacy_policy'], name='entities_in_is_acti_bbedff_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['preferred_contact_medium', 'allows_marketing'], name='entities_in_preferr_075622_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['accepts_privacy_policy', 'allows_marketing'], name='entities_in_accepts_9bf09a_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['person', 'is_active'], name='entities_in_person__5d090e_idx'),
        ),
        migrations.AddIndex(
            model_name='individualprofile',
            index=models.Index(fields=['academic_degree', 'preferred_contact_medium'], name='entities_in_academi_e3d4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'marital_status'], name='entities_pe_is_acti_60b273_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'birthday'], name='entities_pe_is_acti_e3ff5c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender', 'country_of_nationality'], name='entities_pe_gender_e455c8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['marital_status', 'gender'], name='entities_pe_marital_a02f17_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='entities_pe_created_0a4745_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['updated_at'], name='entities_pe_updated_ab13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'created_at'], name='entities_pe_is_acti_4ade97_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactdetail',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('organization__isnull', False), _connector='OR'), name='contact_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='contactdetail',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('organization__isnull', False), _negated=True), name='contact_single_owner_only'),
        ),
    ]
