# Generated by Django 5.2.1 on 2025-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_add_optimized_indexes'),
        ('world', '0002_academicdegree_world_acade_is_acti_c4ce00_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='entities_pe_first_n_a92eb5_idx',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fathers_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='mothers_name',
            new_name='second_last_name',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='entities_pe_first_n_60102d_idx'),
        ),
    ]
