# Generated by Django 5.2.1 on 2025-09-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_convert_gender_marital_status_to_foreign_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_gender__522465_idx',
            old_name='entities_pe_gender_89874f_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_marital_32e17d_idx',
            old_name='entities_pe_marital_e1e6f0_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_is_acti_11ce92_idx',
            old_name='entities_pe_is_acti_f517d0_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_is_acti_8e6b7f_idx',
            old_name='entities_pe_is_acti_60b273_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_gender__633dfc_idx',
            old_name='entities_pe_gender_e455c8_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='entities_pe_marital_2f7a66_idx',
            old_name='entities_pe_marital_a02f17_idx',
        ),
    ]
