# Generated by Django 5.2.1 on 2025-09-24 21:44

from django.db import migrations, connection


def safe_rename_indexes(apps, schema_editor):
    """
    Safely rename indexes, checking if they exist first.
    This handles the case where indexes may have already been renamed
    by previous migrations or may not exist at all.
    """
    with connection.cursor() as cursor:
        # List of index renames to attempt
        index_renames = [
            ('entities_pe_gender_89874f_idx', 'entities_pe_gender__522465_idx'),
            ('entities_pe_marital_e1e6f0_idx', 'entities_pe_marital_32e17d_idx'),
            ('entities_pe_is_acti_f517d0_idx', 'entities_pe_is_acti_11ce92_idx'),
            ('entities_pe_is_acti_60b273_idx', 'entities_pe_is_acti_8e6b7f_idx'),
            ('entities_pe_gender_e455c8_idx', 'entities_pe_gender__633dfc_idx'),
            ('entities_pe_marital_a02f17_idx', 'entities_pe_marital_2f7a66_idx'),
        ]
        
        for old_name, new_name in index_renames:
            try:
                # Check if the old index exists
                cursor.execute("""
                    SELECT indexname FROM pg_indexes 
                    WHERE indexname = %s
                """, [old_name])
                
                if cursor.fetchone():
                    # Check if the new index already exists
                    cursor.execute("""
                        SELECT indexname FROM pg_indexes 
                        WHERE indexname = %s
                    """, [new_name])
                    
                    if not cursor.fetchone():
                        # Old index exists, new one doesn't, safe to rename
                        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
                        print(f"Renamed index {old_name} to {new_name}")
                    else:
                        print(f"Index {new_name} already exists, skipping rename of {old_name}")
                else:
                    print(f"Index {old_name} does not exist, skipping rename")
                    
            except Exception as e:
                print(f"Error handling index {old_name}: {e}")
                # Continue with other indexes even if one fails


def reverse_safe_rename_indexes(apps, schema_editor):
    """
    Reverse the index renames.
    """
    with connection.cursor() as cursor:
        # List of index renames to reverse
        index_renames = [
            ('entities_pe_gender__522465_idx', 'entities_pe_gender_89874f_idx'),
            ('entities_pe_marital_32e17d_idx', 'entities_pe_marital_e1e6f0_idx'),
            ('entities_pe_is_acti_11ce92_idx', 'entities_pe_is_acti_f517d0_idx'),
            ('entities_pe_is_acti_8e6b7f_idx', 'entities_pe_is_acti_60b273_idx'),
            ('entities_pe_gender__633dfc_idx', 'entities_pe_gender_e455c8_idx'),
            ('entities_pe_marital_2f7a66_idx', 'entities_pe_marital_a02f17_idx'),
        ]
        
        for new_name, old_name in index_renames:
            try:
                # Check if the new index exists
                cursor.execute("""
                    SELECT indexname FROM pg_indexes 
                    WHERE indexname = %s
                """, [new_name])
                
                if cursor.fetchone():
                    # Check if the old index already exists
                    cursor.execute("""
                        SELECT indexname FROM pg_indexes 
                        WHERE indexname = %s
                    """, [old_name])
                    
                    if not cursor.fetchone():
                        # New index exists, old one doesn't, safe to rename back
                        cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')
                        print(f"Renamed index {new_name} back to {old_name}")
                    else:
                        print(f"Index {old_name} already exists, skipping reverse rename of {new_name}")
                else:
                    print(f"Index {new_name} does not exist, skipping reverse rename")
                    
            except Exception as e:
                print(f"Error handling index {new_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_fix_index_names'),
    ]

    operations = [
        migrations.RunPython(
            safe_rename_indexes,
            reverse_safe_rename_indexes,
        ),
    ]
