# Generated by Django 5.2.1 on 2025-09-29 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_move_medium_to_touchpoint_and_rename_touchpointclass'),
        ('our_institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Web Agent',
                'verbose_name_plural': 'Web Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('interactions.agent',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150)),
                ('base_url', models.URLField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.channel')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_institution.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visitor_cookie', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('referrer_url', models.URLField(blank=True, default='')),
                ('landing_page_url', models.URLField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('conversion_events', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_sessions', to='interactions.agent')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='websites.website')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['visitor_cookie', 'started_at'], name='websites_we_visitor_d49e16_idx'), models.Index(fields=['website', 'started_at'], name='websites_we_website_d809b9_idx'), models.Index(fields=['session_id'], name='websites_we_session_1170a7_idx'), models.Index(fields=['utm_source', 'utm_medium'], name='websites_we_utm_sou_4ef971_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebInteraction',
            fields=[
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s', serialize=False, to='interactions.interaction')),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('visitor_cookie', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('client_hints', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('element', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', 'created_at'], name='websites_we_website_0cf87f_idx'), models.Index(fields=['session_id'], name='websites_we_session_3f20b7_idx'), models.Index(fields=['visitor_cookie'], name='websites_we_visitor_1128bb_idx'), models.Index(fields=['utm_source', 'utm_medium', 'utm_campaign'], name='websites_we_utm_sou_2de9f0_idx')],
            },
        ),
    ]
