# Generated by Django 5.2.1 on 2025-09-19 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0003_touchpoint_content_type'),
        ('our_institution', '0001_initial'),
        ('products', '0004_add_included_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150)),
                ('base_url', models.URLField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_institution.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebSurface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('path', models.CharField(help_text="Path starting with '/', e.g. /products/crm", max_length=512)),
                ('exact_match', models.BooleanField(default=True, help_text='If False, acts as a prefix')),
                ('regex', models.CharField(blank=True, default='', help_text='Optional regex to match paths', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('is_thankyou', models.BooleanField(default=False)),
                ('is_form', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('touchpoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_surface', to='interactions.touchpoint')),
                ('touchpoint_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_surfaces', to='interactions.touchpointclass')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='websites.website')),
            ],
            options={
                'ordering': ['website__name', 'path'],
            },
        ),
        migrations.CreateModel(
            name='UrlRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('kind', models.CharField(choices=[('exact', 'Exact'), ('prefix', 'Prefix'), ('regex', 'Regex')], default='exact', max_length=10)),
                ('pattern', models.CharField(max_length=512)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='websites.website')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='websites.websurface')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebForm',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('websites.websurface',),
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('websites.websurface',),
        ),
        migrations.CreateModel(
            name='WebInteraction',
            fields=[
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s', serialize=False, to='interactions.interaction')),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('visitor_cookie', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('client_hints', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('element', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', 'created_at'], name='websites_we_website_0cf87f_idx'), models.Index(fields=['session_id'], name='websites_we_session_3f20b7_idx'), models.Index(fields=['visitor_cookie'], name='websites_we_visitor_1128bb_idx'), models.Index(fields=['utm_source', 'utm_medium', 'utm_campaign'], name='websites_we_utm_sou_2de9f0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='websurface',
            index=models.Index(fields=['website', 'path'], name='websites_we_website_e9bcea_idx'),
        ),
        migrations.AddIndex(
            model_name='websurface',
            index=models.Index(fields=['touchpoint_class'], name='websites_we_touchpo_98743f_idx'),
        ),
        migrations.AddIndex(
            model_name='websurface',
            index=models.Index(fields=['is_form', 'is_thankyou'], name='websites_we_is_form_d855b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='websurface',
            constraint=models.CheckConstraint(condition=models.Q(('path__startswith', '/')), name='websurface_path_starts_with_slash'),
        ),
        migrations.AlterUniqueTogether(
            name='websurface',
            unique_together={('website', 'path', 'is_form', 'is_thankyou')},
        ),
        migrations.AlterUniqueTogether(
            name='urlroutingrule',
            unique_together={('website', 'pattern', 'surface')},
        ),
    ]
