# Generated by Django 5.2.1 on 2025-09-23 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        # Create WebSession model
        migrations.CreateModel(
            name='WebSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visitor_cookie', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('referrer_url', models.URLField(blank=True, default='')),
                ('landing_page_url', models.URLField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('conversion_events', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_sessions', to='interactions.agent')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='websites.website')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        
        # Add indexes for WebSession
        migrations.AddIndex(
            model_name='websession',
            index=models.Index(fields=['visitor_cookie', 'started_at'], name='websites_we_visitor_2a8b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='websession',
            index=models.Index(fields=['website', 'started_at'], name='websites_we_website_8b8b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='websession',
            index=models.Index(fields=['session_id'], name='websites_we_session_8b8b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='websession',
            index=models.Index(fields=['utm_source', 'utm_medium'], name='websites_we_utm_sou_8b8b8a_idx'),
        ),
        
        # Note: We'll add the session relationship in a future migration
        # after we have the WebSession model created
    ]
