# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webinteraction',
            name='websites_we_session_3f20b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='webinteraction',
            name='websites_we_visitor_1128bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='websession',
            name='websites_we_session_1170a7_idx',
        ),
        migrations.AlterField(
            model_name='websession',
            name='session_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
