# Generated by Django 5.2.1 on 2025-09-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_add_touchpoint_is_active_index'),
        ('websites', '0002_auto_20250923_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Web Agent',
                'verbose_name_plural': 'Web Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('interactions.agent',),
        ),
        migrations.RenameIndex(
            model_name='websession',
            new_name='websites_we_visitor_d49e16_idx',
            old_name='websites_we_visitor_2a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='websession',
            new_name='websites_we_website_d809b9_idx',
            old_name='websites_we_website_8b8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='websession',
            new_name='websites_we_session_1170a7_idx',
            old_name='websites_we_session_8b8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='websession',
            new_name='websites_we_utm_sou_4ef971_idx',
            old_name='websites_we_utm_sou_8b8b8a_idx',
        ),
        migrations.AddField(
            model_name='website',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.channel'),
        ),
    ]
