# Generated by Django 5.2.1 on 2025-09-24 17:51

from django.db import migrations
from urllib.parse import urlparse


def backfill_website_channels(apps, schema_editor):
    """Backfill channels for existing websites."""
    Website = apps.get_model('websites', 'Website')
    Channel = apps.get_model('interactions', 'Channel')
    Medium = apps.get_model('interactions', 'Medium')
    
    # Get or create the owned_website medium
    medium, _ = Medium.objects.get_or_create(
        code='owned_website',
        defaults={'name': 'Owned Website'}
    )
    
    # Process websites without channels
    websites_without_channels = Website.objects.filter(channel__isnull=True)
    
    for website in websites_without_channels:
        try:
            # Extract domain name
            parsed = urlparse(website.base_url)
            domain = parsed.netloc.lower()
            if domain.startswith('www.'):
                domain = domain[4:]
            
            # Create channel name
            if domain.endswith('.com'):
                domain_part = domain.replace('.com', '')
                channel_name = f"{domain_part.title()}.com Website"
            elif domain.endswith('.edu.pe'):
                domain_part = domain.replace('.edu.pe', '')
                channel_name = f"{domain_part.upper()} University"
            elif domain.endswith('.edu'):
                domain_part = domain.replace('.edu', '')
                channel_name = f"{domain_part.title()} University"
            else:
                channel_name = f"{domain.title()}"
            
            # Create or get channel
            channel, _ = Channel.objects.get_or_create(
                code=domain,
                defaults={
                    'name': channel_name,
                    'medium': medium
                }
            )
            
            # Assign channel to website
            website.channel = channel
            website.save(update_fields=['channel'])
            
            print(f"✅ Backfilled channel for {website.name}: {channel.name}")
            
        except Exception as e:
            print(f"❌ Error backfilling channel for {website.name}: {e}")


def reverse_backfill_website_channels(apps, schema_editor):
    """Remove channels from websites (reverse operation)."""
    Website = apps.get_model('websites', 'Website')
    Website.objects.update(channel=None)


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_webagent_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_website_channels,
            reverse_backfill_website_channels,
        ),
    ]
