# Generated by Django 5.2.1 on 2025-08-25 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('our_institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalUserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Exitoso'), ('login_failed', 'Login Fallido'), ('password_changed', 'Cambio de Contraseña'), ('permissions_changed', 'Cambio de Permisos'), ('profile_updated', 'Perfil Actualizado')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Crítico de Usuario',
                'verbose_name_plural': 'Eventos Críticos de Usuario',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_criti_user_id_d5ce46_idx'), models.Index(fields=['event_type', 'timestamp'], name='users_criti_event_t_4d525a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('prefered_locale', models.CharField(default='es-PE', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('employee_id', models.CharField(blank=True, help_text='ID único del empleado', max_length=20, null=True, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_institution.division')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staffprofile')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_institution.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Staff',
                'verbose_name_plural': 'Perfiles de Staff',
                'indexes': [models.Index(fields=['is_active'], name='users_staff_is_acti_a83826_idx'), models.Index(fields=['division'], name='users_staff_divisio_30d595_idx'), models.Index(fields=['position'], name='users_staff_positio_a0330a_idx'), models.Index(fields=['verified'], name='users_staff_verifie_a3587e_idx'), models.Index(fields=['manager'], name='users_staff_manager_383c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('preferred_contact_medium', models.CharField(choices=[('EM', 'Email'), ('TX', 'Texto'), ('PH', 'Teléfono'), ('VD', 'Videollamada'), ('IP', 'Presencial'), ('NN', 'Desconocido')], default='EM', max_length=2)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('custom_filters', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias del Usuario',
                'verbose_name_plural': 'Preferencias del Usuario',
                'indexes': [models.Index(fields=['user'], name='users_userp_user_id_f3ab16_idx'), models.Index(fields=['preferred_contact_medium'], name='users_userp_preferr_68f139_idx'), models.Index(fields=['notifications_enabled'], name='users_userp_notific_5d65d5_idx'), models.Index(fields=['is_active'], name='users_userp_is_acti_198b0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'indexes': [models.Index(fields=['user', 'login_time'], name='users_users_user_id_083804_idx'), models.Index(fields=['login_time'], name='users_users_login_t_4b988a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(choices=[('default', 'Genérica (gris)'), ('primary', 'Principal (azul)'), ('success', 'Éxito (verde)'), ('info', 'Informativa (celeste)'), ('warning', 'Alerta (ámbar)'), ('danger', 'Peligro (rojo)'), ('pink', 'Rosa'), ('orange', 'Naranja'), ('fucsia', 'Fucsia')], default='default', max_length=10)),
                ('representative', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiqueta de Usuario',
                'verbose_name_plural': 'Etiquetas de Usuario',
                'indexes': [models.Index(fields=['representative'], name='users_usert_represe_162a77_idx'), models.Index(fields=['tag_type'], name='users_usert_tag_typ_91ab59_idx'), models.Index(fields=['is_active'], name='users_usert_is_acti_4b815e_idx')],
                'unique_together': {('representative', 'name')},
            },
        ),
    ]
