# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='users_staff_divisio_30d595_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='users_staff_positio_a0330a_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='users_staff_manager_383c4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpreference',
            name='users_userp_user_id_f3ab16_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertag',
            name='users_usert_represe_162a77_idx',
        ),
    ]
