# Generated by Django 5.2.1 on 2026-05-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usersession_session_duration_minutes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='users_staff_is_acti_a83826_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='users_staff_verifie_a3587e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpreference',
            name='users_userp_preferr_68f139_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpreference',
            name='users_userp_notific_5d65d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpreference',
            name='users_userp_is_acti_198b0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertag',
            name='users_usert_tag_typ_91ab59_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertag',
            name='users_usert_is_acti_4b815e_idx',
        ),
    ]
