# Generated by Django 5.2.1 on 2025-09-25 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('products', '0001_initial'),
        ('world', '0002_populate_world_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='interaction_is_acti_0bd990_idx'), models.Index(fields=['code'], name='interaction_code_cbcaf3_idx'), models.Index(fields=['name'], name='interaction_name_20ac5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='interactions.actiontype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('agent_type', models.CharField(choices=[('browser', 'Navegador Web'), ('human', 'Humano'), ('system', 'Sistema externo'), ('device', 'Dispositivo físico'), ('bot', 'Bot automatizado'), ('ai', 'Agente de Inteligencia Artificial'), ('other', 'Otro')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('operated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_operated', to='entities.person')),
                ('represents_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_representing_as_organization', to='entities.organization')),
                ('represents_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_representing_as_person', to='entities.person')),
            ],
            options={
                'ordering': ['agent_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('external', 'Fuente Externa'), ('owned', 'Propiedad Propia'), ('direct', 'Tráfico Directo'), ('unknown', 'Fuente Desconocida')], default='external', help_text='Tipo de fuente de tráfico', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='interaction_is_acti_a3fc29_idx'), models.Index(fields=['code'], name='interaction_code_9eb7c0_idx'), models.Index(fields=['name'], name='interaction_name_96e25e_idx'), models.Index(fields=['source_type'], name='interaction_source__3509c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('communication_type', models.CharField(choices=[('synchronous', 'Comunicación Síncrona'), ('asynchronous', 'Comunicación Asíncrona'), ('real_time', 'Tiempo Real'), ('batch', 'Por Lotes')], default='asynchronous', help_text='Tipo de comunicación que soporta este medium', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='interaction_is_acti_dc1aaf_idx'), models.Index(fields=['code'], name='interaction_code_1bcba3_idx'), models.Index(fields=['name'], name='interaction_name_1f81fe_idx'), models.Index(fields=['communication_type'], name='interaction_communi_754577_idx')],
            },
        ),
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, choices=[('affinity', 'Afinidad'), ('category', 'Categoría'), ('product', 'Producto'), ('brand', 'Marca')], help_text='Clasificación del enfoque estratégico del contenido asociado a este touchpoint', max_length=20, null=True, verbose_name='Tipo de contenido comunicacional')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Miembro del equipo responsable de este punto de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_touchpoints', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, help_text='Canal de tráfico (DÓNDE vino la interacción)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='interactions.channel')),
                ('medium', models.ForeignKey(blank=True, help_text='Método de comunicación (CÓMO se comunica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='interactions.medium')),
                ('product', models.ForeignKey(blank=True, help_text='Producto principal asociado a este punto de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='products.product')),
                ('related_descriptors', models.ManyToManyField(blank=True, to='world.worlddescriptor')),
                ('related_functions', models.ManyToManyField(blank=True, to='world.functionorresponsibility')),
                ('related_industries', models.ManyToManyField(blank=True, to='world.industry')),
                ('related_skills', models.ManyToManyField(blank=True, to='world.skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.action')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='interactions.agent')),
                ('organization', models.ForeignKey(blank=True, help_text='Optional organization for corporate customers (B2B). Leave empty for individual customers (B2C).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='entities.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='entities.person')),
                ('product', models.ForeignKey(blank=True, help_text='Producto vinculado a esta interacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='products.product')),
                ('representative', models.ForeignKey(blank=True, help_text='Miembro de la organización que ejecutó esta interacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_represented', to=settings.AUTH_USER_MODEL)),
                ('touchpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.touchpoint')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TouchpointType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='interaction_is_acti_a594ce_idx'), models.Index(fields=['code'], name='interaction_code_967f4c_idx'), models.Index(fields=['name'], name='interaction_name_c9be4b_idx')],
            },
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='touchpoint_type',
            field=models.ForeignKey(blank=True, help_text='Tipo funcional (QUÉ tipo de touchpoint)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='interactions.touchpointtype'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['is_active'], name='interaction_is_acti_87e7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['code'], name='interaction_code_109c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['name'], name='interaction_name_2476f1_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_type'], name='interaction_agent_t_52aaef_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['identifier'], name='interaction_identif_69aa2d_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active'], name='interaction_is_acti_2ca2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['operated_by'], name='interaction_operate_26a060_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['represents_person'], name='interaction_represe_d9f885_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['represents_organization'], name='interaction_represe_c03172_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['is_active'], name='interaction_is_acti_d47b50_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['person'], name='interaction_person__42ba96_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['organization'], name='interaction_organiz_dd7c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['touchpoint'], name='interaction_touchpo_f8c7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['action'], name='interaction_action__340dda_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['agent'], name='interaction_agent_i_53e7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['representative'], name='interaction_represe_1e217f_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['occurred_at'], name='interaction_occurre_0f80c7_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['is_active', 'occurred_at'], name='interaction_is_acti_505cde_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['touchpoint', 'is_active'], name='interaction_touchpo_7bfe29_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['session_id'], name='interaction_session_40851a_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['ip_address'], name='interaction_ip_addr_7e6957_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['duration_seconds'], name='interaction_duratio_52a6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['source'], name='interaction_source_ac78a5_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['touchpoint', 'occurred_at'], name='interaction_touchpo_b35b65_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['agent', 'occurred_at'], name='interaction_agent_i_37766e_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['is_active'], name='interaction_is_acti_541d27_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['touchpoint_type'], name='interaction_touchpo_9b9eca_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['code'], name='interaction_code_f7eec3_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['name'], name='interaction_name_fe1d60_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['channel'], name='interaction_channel_83fcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['medium'], name='interaction_medium__c8423d_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['channel', 'medium'], name='interaction_channel_3ccace_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['medium', 'touchpoint_type'], name='interaction_medium__876ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['channel', 'touchpoint_type'], name='interaction_channel_490bb7_idx'),
        ),
    ]
