# Generated by Django 5.2.1 on 2025-10-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_move_medium_to_touchpoint_and_rename_touchpointclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpoint',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent touchpoint for hierarchical organization (e.g., campaign-level child of source-level parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='interactions.touchpoint'),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
