# Generated by Django 5.2.1 on 2025-06-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='jtbd_stage',
            field=models.CharField(blank=True, choices=[('any', 'Cualquiera'), ('job_oblivious', 'Trabajo Desconocido'), ('job_awareness', 'Conciencia del Trabajo'), ('job_research', 'Investigación'), ('job_decision', 'Toma de decisión'), ('job_execution', 'Ejecución'), ('job_solved', 'Resuelto'), ('stage_unknown', 'Etapa Desconocida')], default='any', help_text='Etapa del proceso de progreso del cliente (Jobs to Be Done)', max_length=50, verbose_name='Etapa JTBD'),
        ),
    ]
