# Generated by Django 5.2.1 on 2025-10-06 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_add_parent_field_to_touchpoint'),
        ('products', '0002_alter_product_included_products'),
        ('world', '0002_populate_world_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchpoint',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='touchpoint',
            unique_together={('code', 'url')},
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['url'], name='interaction_url_ed1c7a_idx'),
        ),
    ]
