# Generated by Django 5.2.1 on 2025-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_interaction_jtbd_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpoint',
            name='content_type',
            field=models.CharField(blank=True, choices=[('affinity', 'Afinidad'), ('category', 'Categoría'), ('product', 'Producto'), ('brand', 'Marca')], help_text='Clasificación del enfoque estratégico del contenido asociado a este touchpoint', max_length=20, null=True, verbose_name='Tipo de contenido comunicacional'),
        ),
    ]
