# Generated by Django 5.2.1 on 2026-02-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_add_unique_together_code_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agent',
            name='interaction_operate_26a060_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='interaction_represe_d9f885_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='interaction_represe_c03172_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_person__42ba96_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_organiz_dd7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_touchpo_f8c7a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_action__340dda_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_agent_i_53e7d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_represe_1e217f_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_ip_addr_7e6957_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_duratio_52a6c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_source_ac78a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='touchpoint',
            name='interaction_channel_83fcbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='touchpoint',
            name='interaction_medium__c8423d_idx',
        ),
    ]
