# Generated by Django 5.2.1 on 2025-09-20 19:54

from django.db import migrations, models
from django.db.models import deletion


def move_channels_to_touchpoints(apps, schema_editor):
    """
    Move channel relationships from interactions to touchpoints.
    For each interaction with a channel, update its touchpoint to have that channel.
    """
    Interaction = apps.get_model('interactions', 'Interaction')
    Touchpoint = apps.get_model('interactions', 'Touchpoint')
    
    # Get all interactions that have both a touchpoint and a channel
    interactions_with_channels = Interaction.objects.filter(
        touchpoint__isnull=False,
        channel__isnull=False
    ).select_related('touchpoint', 'channel')
    
    updated_touchpoints = set()
    
    for interaction in interactions_with_channels:
        touchpoint = interaction.touchpoint
        channel = interaction.channel
        
        # Only update if the touchpoint doesn't already have a channel
        if not touchpoint.channel_id:
            touchpoint.channel = channel
            touchpoint.save(update_fields=['channel'])
            updated_touchpoints.add(touchpoint.id)
    
    print(f"Updated {len(updated_touchpoints)} touchpoints with channel information")


def reverse_move_channels_to_touchpoints(apps, schema_editor):
    """
    Reverse migration: move channels back from touchpoints to interactions.
    This is a best-effort approach since we can't perfectly restore the original state.
    """
    Interaction = apps.get_model('interactions', 'Interaction')
    Touchpoint = apps.get_model('interactions', 'Touchpoint')
    
    # Get all interactions that have touchpoints with channels
    interactions_with_touchpoint_channels = Interaction.objects.filter(
        touchpoint__isnull=False,
        touchpoint__channel__isnull=False
    ).select_related('touchpoint', 'touchpoint__channel')
    
    updated_interactions = 0
    
    for interaction in interactions_with_touchpoint_channels:
        if not interaction.channel_id:
            interaction.channel = interaction.touchpoint.channel
            interaction.save(update_fields=['channel'])
            updated_interactions += 1
    
    print(f"Restored channel to {updated_interactions} interactions")


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_touchpoint_content_type'),
    ]

    operations = [
        # Step 1: Add channel field to Touchpoint
        migrations.AddField(
            model_name='touchpoint',
            name='channel',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=deletion.SET_NULL, 
                related_name='touchpoints', 
                to='interactions.channel',
                help_text="Canal a través del cual se organiza este punto de contacto"
            ),
        ),
        
        # Step 2: Add index for the new channel field
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['channel'], name='interactions_touchpoint_channel_idx'),
        ),
        
        # Step 3: Migrate data from interactions to touchpoints
        migrations.RunPython(
            move_channels_to_touchpoints,
            reverse_move_channels_to_touchpoints,
        ),
        
        # Step 4: Remove channel field from Interaction
        migrations.RemoveField(
            model_name='interaction',
            name='channel',
        ),
    ]
