# Generated by Django 5.2.1 on 2026-05-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_remove_redundant_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='interaction_is_acti_87e7e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='interaction_code_109c9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='interaction_name_2476f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='actiontype',
            name='interaction_is_acti_0bd990_idx',
        ),
        migrations.RemoveIndex(
            model_name='actiontype',
            name='interaction_code_cbcaf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='actiontype',
            name='interaction_name_20ac5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='interaction_is_acti_2ca2ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='interaction_is_acti_a3fc29_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='interaction_code_9eb7c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='interaction_name_96e25e_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='interaction_source__3509c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='medium',
            name='interaction_is_acti_dc1aaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='medium',
            name='interaction_code_1bcba3_idx',
        ),
        migrations.RemoveIndex(
            model_name='medium',
            name='interaction_name_1f81fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='medium',
            name='interaction_communi_754577_idx',
        ),
        migrations.RemoveIndex(
            model_name='touchpointtype',
            name='interaction_is_acti_a594ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='touchpointtype',
            name='interaction_code_967f4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='touchpointtype',
            name='interaction_name_c9be4b_idx',
        ),
    ]
