# Generated by Django 5.2.1 on 2025-09-20 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_convert_gender_marital_status_to_foreign_keys'),
        ('interactions', '0004_move_channel_to_touchpoint'),
        ('products', '0004_add_included_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_channel_e8b2f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_channel_000eaf_idx',
        ),
        migrations.RenameIndex(
            model_name='touchpoint',
            new_name='interaction_channel_83fcbc_idx',
            old_name='interactions_touchpoint_channel_idx',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optional organization for corporate customers (B2B). Leave empty for individual customers (B2C).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='entities.organization'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['touchpoint', 'is_active'], name='interaction_touchpo_7bfe29_idx'),
        ),
    ]
