# Generated by Django 5.2.1 on 2025-09-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_add_touchpoint_is_active_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_jtbd_st_2320e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_jtbd_st_5d27e5_idx',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='jtbd_stage',
        ),
        migrations.RemoveField(
            model_name='touchpoint',
            name='funnel_stage',
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Canal al que pertenece este punto de contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='interactions.channel'),
        ),
    ]
